#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World inside

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload
